In [1]:
import numpy as np
from math import sqrt
from pprint import pprint

In [68]:
def rotate_node(Q,x):
    
    x_prime = np.zeros(3)
    
    for i in range(3):
        for j in range(3):
            x_prime[i] += Q[i][j] * x[j]
    
    return x_prime

def rotate_nodes(Q,xx):
    
    N = xx.shape[1]
    
    xx_prime = np.zeros(xx.shape)
    
    pprint(x_prime)
    
    for n in 
        for i in range(3):
            for j in range(3):
                x_prime[i] += Q[i][j] * x[j]
    
    return x_prime

def trans_matrix(M):
    """Take the transpose of a matrix."""
    n = len(M)
    return [[ M[i][j] for i in range(n)] for j in range(n)]

def norm(x):
    """Return the Euclidean norm of the vector x."""
    return sqrt(sum([x_i**2 for x_i in x]))

def sign(x):
    if x < 0:
        return -1
    else:
        return 1

def householder(x):
    e0 =[1.0,0.0,0.0]
    alpha = -sign(x[0]) * norm(x)
    u = list(map(lambda p,q: p + alpha * q, x, e0))
    norm_u = norm(u)
    v = list(map(lambda p: p / norm_u, u))
    
    Q = [ [float(i==j) - 2.0 * v[i] * v[j] for i in range(3)] for j in range(3) ]

    return Q

In [69]:
Nh = 4
xx = np.loadtxt("md/md."+str(Nh).zfill(5),usecols = (0,1,2)).T
pprint(xx)
pprint(householder(xx[:,0]))
pprint(rotate_node(householder(xx[:,0]),xx[:,0]))

array([[ 0.        ,  0.94280904, -0.47140452, -0.47140452],
       [ 0.        ,  0.        ,  0.81649658, -0.81649658],
       [ 1.        , -0.33333333, -0.33333333, -0.33333333]])
[[2.2204460492503131e-16, 0.0, 0.99999999999999978],
 [0.0, 1.0, 0.0],
 [0.99999999999999978, 0.0, 2.2204460492503131e-16]]
array([ 0.,  0.,  0.])
array([  1.00000000e+00,   0.00000000e+00,   2.22044605e-16])


In [ ]:
from numpy.polynomial.laguerre import lagval
print(lagval(0,[1,0,0,0]))